#!/usr/bin/env python3
"""Generate one static HTML page for every public artwork in site-data.json.

V8.2 STEP 1 + STEP 2 responsibilities:
- validate artwork IDs before touching existing generated pages;
- create /works/<artworkId>.html from one shared template;
- skip non-public records;
- remove stale pages created by this generator only;
- write a deterministic manifest;
- generate Canonical, Open Graph, Twitter Card and VisualArtwork JSON-LD;
- print a complete summary suitable for GitHub Actions logs.

STEP 3 adds share controls for mobile Web Share API and desktop share/copy flow.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, quote, urlencode, urljoin, urlparse, urlunparse

BASE_URL = "https://siyuye.github.io/XieXiuYing1960/"
SITE_NAME = "謝秀英書畫藝術館"
ARTIST_NAME = "謝秀英"
GENERATED_MARKER = "<!-- GENERATED BY scripts/generate_artwork_pages.py; DO NOT EDIT DIRECTLY -->"
ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def fail(message: str) -> None:
    print(f"::error::{message}", file=sys.stderr)
    raise SystemExit(1)


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"找不到檔案：{path}")
    except json.JSONDecodeError as exc:
        fail(f"JSON 格式錯誤：{path}（第 {exc.lineno} 行，第 {exc.colno} 欄）")


def text(value: Any) -> str:
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def is_public(artwork: dict[str, Any]) -> bool:
    value = artwork.get("isPublic", artwork.get("public", True))
    if isinstance(value, bool):
        return value
    return text(value).upper() not in {"FALSE", "0", "NO", "N", "OFF"}


def artwork_id(artwork: dict[str, Any]) -> str:
    value = text(artwork.get("artworkId") or artwork.get("id")).upper()
    if not value:
        fail("公開作品缺少 artworkId / id")
    if not ID_RE.fullmatch(value):
        fail(f"作品編號含不安全字元：{value}")
    return value


def absolute_url(value: Any) -> str:
    raw = text(value)
    if not raw:
        return ""
    parsed = urlparse(raw)
    if parsed.scheme in {"http", "https"}:
        return raw
    return urljoin(BASE_URL, raw.lstrip("/"))


def append_version_query(url: str, version: str, key: str = "v") -> str:
    if not url or not version:
        return url
    parsed = urlparse(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query[key] = version
    return urlunparse(parsed._replace(query=urlencode(query)))


def image_url(artwork: dict[str, Any], data_version: str = "") -> str:
    # 官網作品頁大圖維持原有來源，不因社群預覽圖調整而改變。
    direct = artwork.get("imageUrl") or artwork.get("image") or artwork.get("thumbUrl")
    if direct:
        return append_version_query(absolute_url(direct), data_version)
    aid = artwork_id(artwork)
    return append_version_query(urljoin(BASE_URL, f"images/artworks/2400/{quote(aid)}.webp"), data_version)


def social_preview_image_url(artwork: dict[str, Any], data_version: str = "") -> str:
    """Return the existing 1200-long-edge artwork for link preview metadata.

    V8.2.12 intentionally keeps the artwork page/display image independent from
    Open Graph, Twitter Card and JSON-LD preview images.  The preview always
    points to the site's original 1200 library so Facebook does not download
    the 2400 artwork merely to build a link card.
    """
    aid = artwork_id(artwork)
    preview = urljoin(BASE_URL, f"images/artworks/1200/{quote(aid)}.webp")
    return append_version_query(preview, data_version)


def split_terms(value: Any) -> list[str]:
    if isinstance(value, list):
        values = value
    else:
        raw = text(value)
        values = re.split(r"[、,，;；|｜/]+", raw) if raw else []
    output: list[str] = []
    for item in values:
        cleaned = text(item)
        if cleaned and cleaned not in output:
            output.append(cleaned)
    return output


def first(artwork: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = text(artwork.get(key))
        if value:
            return value
    return ""


def seo_title(artwork: dict[str, Any]) -> str:
    title_zh = first(artwork, "titleZh", "nameZh", "title") or artwork_id(artwork)
    title_en = first(artwork, "titleEn", "nameEn")
    artwork_type = first(artwork, "artworkTypeName", "categoryZh", "artworkType", "typeName")
    subjects = split_terms(artwork.get("subjectNames") or artwork.get("subjectName") or artwork.get("subject"))
    classification = "".join([part for part in [artwork_type, *subjects] if part])
    if classification:
        classification += "作品"
    parts = [title_zh or title_en, classification, ARTIST_NAME]
    return "｜".join([part for part in parts if part])


def seo_description(artwork: dict[str, Any]) -> str:
    title_zh = first(artwork, "titleZh", "nameZh", "title") or artwork_id(artwork)
    title_en = first(artwork, "titleEn", "nameEn")
    artwork_type = first(artwork, "artworkTypeName", "categoryZh", "artworkType", "typeName")
    subjects = split_terms(artwork.get("subjectNames") or artwork.get("subjectName") or artwork.get("subject"))
    year = first(artwork, "year", "creationYear", "dateCreated")
    size = first(artwork, "size", "dimensions", "artworkSize")
    description = f"《{title_zh}》"
    if title_en and title_en != title_zh:
        description += f"（{title_en}）"
    description += f"為{ARTIST_NAME}作品"
    details: list[str] = []
    if artwork_type:
        details.append(f"作品類型：{artwork_type}")
    if subjects:
        details.append(f"題材：{'、'.join(subjects)}")
    if year:
        details.append(f"年份：{year}")
    if size:
        details.append(f"尺寸：{size}")
    if details:
        description += "，" + "；".join(details)
    return text(description + f"。收錄於{SITE_NAME}。")


def json_ld(artwork: dict[str, Any], canonical: str, image: str) -> str:
    aid = artwork_id(artwork)
    title_zh = first(artwork, "titleZh", "nameZh", "title") or aid
    title_en = first(artwork, "titleEn", "nameEn")
    artwork_type = first(artwork, "artworkTypeName", "categoryZh", "artworkType", "typeName")
    subjects = split_terms(artwork.get("subjectNames") or artwork.get("subjectName") or artwork.get("subject"))
    year = first(artwork, "year", "creationYear", "dateCreated")
    medium = first(artwork, "mediumNames", "mediumName", "medium")
    material = first(artwork, "materialNames", "materialName", "material")
    size = first(artwork, "size", "dimensions", "artworkSize")
    description = seo_description(artwork)

    data: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": "VisualArtwork",
        "@id": canonical + "#artwork",
        "url": canonical,
        "name": title_zh,
        "identifier": aid,
        "description": description,
        "image": image,
        "inLanguage": "zh-Hant",
        "creator": {
            "@type": "Person",
            "name": ARTIST_NAME,
            "url": BASE_URL,
        },
        "isPartOf": {
            "@type": "WebSite",
            "name": SITE_NAME,
            "url": BASE_URL,
        },
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": canonical,
        },
    }
    if title_en:
        data["alternateName"] = title_en
    if year:
        data["dateCreated"] = year
    if artwork_type:
        data["artform"] = artwork_type
    if medium:
        data["artMedium"] = medium
    if material:
        data["material"] = material
    if subjects:
        data["about"] = [{"@type": "Thing", "name": subject} for subject in subjects]
    if size:
        data["size"] = size

    # Prevent any user-provided text from prematurely closing the script element.
    return json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def detail_rows(artwork: dict[str, Any]) -> str:
    fields = [
        ("年份", first(artwork, "year", "creationYear", "dateCreated")),
        ("尺寸", first(artwork, "size", "dimensions", "artworkSize")),
        ("類型", first(artwork, "artworkTypeName", "categoryZh", "artworkType", "typeName")),
        ("題材", "、".join(split_terms(artwork.get("subjectNames") or artwork.get("subjectName") or artwork.get("subject")))),
        ("材質", first(artwork, "materialNames", "materialName", "material")),
        ("媒材", first(artwork, "mediumNames", "mediumName", "medium")),
    ]
    rows = []
    for label, value in fields:
        if value:
            rows.append(f'<div class="artwork-detail-row"><dt>{html.escape(label)}</dt><dd>{html.escape(value)}</dd></div>')
    return "\n".join(rows) or '<p class="artwork-empty">作品資料整理中。</p>'


def render(template: str, artwork: dict[str, Any], data_version: str = "") -> tuple[str, dict[str, str]]:
    aid = artwork_id(artwork)
    title_zh = first(artwork, "titleZh", "nameZh", "title") or aid
    title_en = first(artwork, "titleEn", "nameEn")
    description_raw = artwork.get("description") or artwork.get("summary") or artwork.get("body") or ""
    description = str(description_raw).replace("\r\n", "\n").replace("\r", "\n").strip()
    page_title = seo_title(artwork)
    meta_description = seo_description(artwork)
    data_version = text(data_version)
    image = image_url(artwork, data_version)
    preview_image = social_preview_image_url(artwork, data_version)
    canonical = urljoin(BASE_URL, f"works/{quote(aid)}.html")
    share_url = append_version_query(canonical, data_version, "share")
    modal_url = urljoin(BASE_URL, f"works.html?id={quote(aid)}")
    image_alt = f"{title_zh} 謝秀英作品"

    replacements = {
        "{{GENERATED_MARKER}}": GENERATED_MARKER,
        "{{PAGE_TITLE}}": html.escape(page_title),
        "{{META_DESCRIPTION}}": html.escape(meta_description, quote=True),
        "{{CANONICAL_URL}}": html.escape(canonical, quote=True),
        "{{SHARE_URL}}": html.escape(share_url, quote=True),
        "{{DATA_VERSION}}": html.escape(data_version, quote=True),
        "{{OG_TITLE}}": html.escape(page_title, quote=True),
        "{{OG_DESCRIPTION}}": html.escape(meta_description, quote=True),
        "{{OG_IMAGE}}": html.escape(preview_image, quote=True),
        "{{OG_IMAGE_ALT}}": html.escape(image_alt, quote=True),
        "{{JSON_LD}}": json_ld(artwork, canonical, preview_image),
        "{{ARTWORK_ID}}": html.escape(aid),
        "{{TITLE_ZH}}": html.escape(title_zh),
        "{{TITLE_EN_BLOCK}}": f'<p class="artwork-title-en" lang="en">{html.escape(title_en)}</p>' if title_en else "",
        "{{IMAGE_URL}}": html.escape(image, quote=True),
        "{{IMAGE_ALT}}": html.escape(image_alt, quote=True),
        "{{DETAIL_ROWS}}": detail_rows(artwork),
        "{{DESCRIPTION_BLOCK}}": f'<section class="artwork-description"><h2>作品介紹</h2><p>{html.escape(description).replace(chr(10), "<br>")}</p></section>' if description else "",
        "{{MODAL_URL}}": html.escape(modal_url, quote=True),
        "{{SHARE_TITLE}}": html.escape(page_title, quote=True),
        "{{SHARE_TEXT}}": html.escape(meta_description, quote=True),
    }
    page = template
    for key, value in replacements.items():
        page = page.replace(key, value)
    unresolved = sorted(set(re.findall(r"\{\{[A-Z0-9_]+\}\}", page)))
    if unresolved:
        fail(f"模板仍有未替換欄位：{', '.join(unresolved)}")
    return page, {
        "artworkId": aid,
        "title": title_zh,
        "path": f"works/{aid}.html",
        "canonical": canonical,
        "image": image,
        "socialPreviewImage": preview_image,
    }


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def clean_stale_pages(output_dir: Path, expected_names: set[str]) -> list[str]:
    removed: list[str] = []
    for path in sorted(output_dir.glob("*.html")):
        if path.name in expected_names:
            continue
        try:
            head = path.read_text(encoding="utf-8")[:500]
        except UnicodeDecodeError:
            continue
        if GENERATED_MARKER in head:
            path.unlink()
            removed.append(path.name)
    return removed


def main() -> None:
    parser = argparse.ArgumentParser(description="建立謝秀英書畫藝術館獨立作品頁")
    parser.add_argument("site_data", type=Path)
    parser.add_argument("template", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--manifest", type=Path)
    args = parser.parse_args()

    payload = load_json(args.site_data)
    if not isinstance(payload, dict) or not isinstance(payload.get("artworks"), list):
        fail("site-data.json 缺少 artworks 陣列")
    try:
        template = args.template.read_text(encoding="utf-8")
    except FileNotFoundError:
        fail(f"找不到作品頁模板：{args.template}")
    if GENERATED_MARKER not in template and "{{GENERATED_MARKER}}" not in template:
        fail("作品頁模板缺少 generated marker")

    records = [a for a in payload["artworks"] if isinstance(a, dict)]
    public_artworks = [a for a in records if is_public(a)]
    skipped_count = len(records) - len(public_artworks)

    # Render everything before deleting or overwriting existing pages.
    rendered: list[tuple[str, str, dict[str, str]]] = []
    seen: set[str] = set()
    for artwork in public_artworks:
        aid = artwork_id(artwork)
        if aid in seen:
            fail(f"公開作品編號重複：{aid}")
        seen.add(aid)
        page, entry = render(template, artwork, text(payload.get("dataVersion")))
        rendered.append((f"{aid}.html", page, entry))

    args.output_dir.mkdir(parents=True, exist_ok=True)
    expected = {name for name, _, _ in rendered}
    removed = clean_stale_pages(args.output_dir, expected)

    created = 0
    unchanged = 0
    for filename, page, _ in rendered:
        if write_if_changed(args.output_dir / filename, page):
            created += 1
        else:
            unchanged += 1

    manifest_path = args.manifest or args.output_dir / "generated-pages.json"
    manifest = {
        "schemaVersion": 2,
        "dataVersion": text(payload.get("dataVersion")),
        "generatedAt": text(payload.get("generatedAt")),
        "count": len(rendered),
        "pages": [entry for _, _, entry in rendered],
    }
    manifest_text = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    manifest_changed = write_if_changed(manifest_path, manifest_text)

    print("========== STEP 1 + STEP 2 作品頁產生結果 ==========")
    print(f"輸入作品紀錄：{len(records)}")
    print(f"公開並產生：{len(rendered)}")
    print(f"非公開略過：{skipped_count}")
    print(f"新增或更新：{created}")
    print(f"內容未變更：{unchanged}")
    print(f"移除過期頁：{len(removed)}")
    for name in removed:
        print(f"  DELETE works/{name}")
    print(f"作品頁清單：{manifest_path}（{'已更新' if manifest_changed else '未變更'}）")
    print("Social SEO：Canonical / Open Graph / Twitter Card / JSON-LD 已產生")
    print("STEP 1 + STEP 2 產生器執行完成")


if __name__ == "__main__":
    main()
