#!/usr/bin/env python3
"""Self-contained acceptance test for V8.2 STEP 1 + STEP 2 artwork pages."""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "scripts" / "generate_artwork_pages.py"
TEMPLATE = ROOT / "templates" / "artwork-page.html"
MARKER = "<!-- GENERATED BY scripts/generate_artwork_pages.py; DO NOT EDIT DIRECTLY -->"


def run(data: dict, work: Path, expect_ok: bool = True) -> subprocess.CompletedProcess[str]:
    source = work / "site-data.json"
    source.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    result = subprocess.run(
        [sys.executable, str(GENERATOR), str(source), str(TEMPLATE), str(work / "works"), "--manifest", str(work / "manifest.json")],
        text=True,
        capture_output=True,
    )
    if expect_ok and result.returncode != 0:
        raise AssertionError(result.stdout + result.stderr)
    if not expect_ok and result.returncode == 0:
        raise AssertionError("預期產生器失敗，但實際成功")
    return result


def main() -> None:
    with tempfile.TemporaryDirectory() as temp:
        work = Path(temp)
        payload = {
            "dataVersion": "TEST001",
            "generatedAt": "2026-07-19T00:00:00+08:00",
            "artworks": [
                {
                    "artworkId": "XH0001",
                    "titleZh": "測試作品",
                    "titleEn": "Test Artwork",
                    "artworkTypeName": "工筆",
                    "subjectNames": ["荷花", "水鳥"],
                    "year": "2026",
                    "size": "60 × 90 cm",
                    "mediumName": "膠彩",
                    "materialName": "絹本",
                    "imageUrl": "artworks/2400/XH0001.webp",
                    "isPublic": True,
                },
                {"artworkId": "XH0002", "titleZh": "不公開作品", "isPublic": False},
            ],
        }
        run(payload, work)
        page = work / "works" / "XH0001.html"
        assert page.exists(), "公開作品頁未產生"
        assert not (work / "works" / "XH0002.html").exists(), "非公開作品不應產生"
        html_text = page.read_text(encoding="utf-8")
        assert MARKER in html_text, "產生頁缺少標記"
        canonical = "https://siyuye.github.io/XieXiuYing1960/works/XH0001.html"
        image = "https://siyuye.github.io/XieXiuYing1960/artworks/2400/XH0001.webp"
        assert f'<link rel="canonical" href="{canonical}">' in html_text, "Canonical 錯誤"
        assert f'<meta property="og:url" content="{canonical}">' in html_text, "og:url 錯誤"
        assert f'<meta property="og:image" content="{image}">' in html_text, "og:image 必須為絕對網址"
        assert '<meta name="twitter:card" content="summary_large_image">' in html_text, "Twitter Card 缺失"
        match = re.search(r'<script type="application/ld\+json">(.*?)</script>', html_text, re.S)
        assert match, "JSON-LD 缺失"
        structured = json.loads(match.group(1))
        assert structured["@type"] == "VisualArtwork", "JSON-LD 類型錯誤"
        assert structured["url"] == canonical, "JSON-LD URL 錯誤"
        assert structured["image"] == image, "JSON-LD 圖片錯誤"
        assert structured["creator"]["name"] == "謝秀英", "JSON-LD creator 錯誤"
        manifest = json.loads((work / "manifest.json").read_text(encoding="utf-8"))
        assert manifest["schemaVersion"] == 2
        assert manifest["count"] == 1
        assert manifest["pages"][0]["canonical"] == canonical

        # A stale generated page must be deleted; a manually maintained page must survive.
        stale = work / "works" / "XH9999.html"
        stale.write_text(MARKER + "\nold", encoding="utf-8")
        manual = work / "works" / "manual.html"
        manual.write_text("manual", encoding="utf-8")
        run(payload, work)
        assert not stale.exists(), "過期自動頁未刪除"
        assert manual.exists(), "不應刪除人工 HTML"

        # JSON-LD must remain safe even when user text contains a closing script token.
        hostile = dict(payload)
        hostile["artworks"] = [
            {
                "artworkId": "XH0003",
                "titleZh": "測試</script><script>alert(1)</script>",
                "imageUrl": "artworks/2400/XH0003.webp",
                "isPublic": True,
            }
        ]
        run(hostile, work)
        hostile_html = (work / "works" / "XH0003.html").read_text(encoding="utf-8")
        assert hostile_html.count('<script type="application/ld+json">') == 1
        json_ld_match = re.search(r'<script type="application/ld\+json">(.*?)</script>', hostile_html, re.S)
        assert json_ld_match
        json.loads(json_ld_match.group(1))
        assert "<\\/script>" in json_ld_match.group(1), "JSON-LD script 結束標籤未安全處理"

        # Restore the original valid output before testing duplicate-ID failure protection.
        run(payload, work)
        assert page.exists()

        # Duplicate public IDs must stop before overwriting/deleting pages.
        duplicate = dict(payload)
        duplicate["artworks"] = [
            {"artworkId": "XH0001", "titleZh": "甲", "isPublic": True},
            {"artworkId": "xh0001", "titleZh": "乙", "isPublic": True},
        ]
        result = run(duplicate, work, expect_ok=False)
        assert "公開作品編號重複" in result.stderr
        assert page.exists(), "驗證失敗時不應破壞原作品頁"

    print("STEP 1 + STEP 2 自動化驗收全部通過")


if __name__ == "__main__":
    main()
